name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
        id: setup-rye
        with:
          enable-cache: true
          cache-prefix: ${{ matrix.python-version }}
          working-directory: py
      - name: Pin python-version ${{ matrix.python-version }}
        working-directory: py
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: rye pin ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: py
        if: steps.setup-rye.outputs.cache-hit != 'true'
        run: rye sync --no-lock
      - name: Run Tests
        working-directory: py
        run: rye run pytest
